# Generated by hand for initial project scaffold.
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Earnings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("views", models.PositiveIntegerField(default=0)),
                ("birr", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="earnings", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]

